### ISSUE TITLE
Call didProcessPriceUpdate in AppDelegate

### ISSUE THREAD

**Issue by Alifar** [johnalanwoods/XMR-Ticker-2.0#1]
Hi there, cool project you have here and I'm playing around with the source code, the only thing is that Swift is pretty new to me though :)

I am trying to call the didProcessPriceUpdate in AppDelegate in another function, but I get an error when using the following code:

self.didProcessPriceUpdate(_ updatedPrice:Quote)

<img width="418" alt="schermafbeelding 2017-01-19 om 10 46 45" src="https://cloud.githubusercontent.com/assets/6464812/22101687/baa0f8ec-de34-11e6-89f3-43f6add883bf.png">

When I remove the above, Xcode tells met to also remove the updatedPrice so I did, it then shows me the following error.

<img width="850" alt="schermafbeelding 2017-01-19 om 10 47 18" src="https://cloud.githubusercontent.com/assets/6464812/22101694/c0f24b9c-de34-11e6-9130-3d3f4e008238.png">

How can I call this the in the correct way?

Thanks in advance.

**Comment by johnalanwoods** [comment]
Hi Alifar,

Thanks for the mail :) glad you are enjoying playing with it!

Happy to help here - where are you putting the reCall function, is it inside AppDelegate?

The didProcessPriceUpdate function is a delegate method which is only implemented inside classes which adhere to the protocol.

Does this make sense?

Best,
John

**Comment by Alifar** [comment]
Hi John, thank you for your quick reply :)

Yes, the reCall function is inside AppDelegate, as also the didProcessPriceUpdate.

If it is not possible use it in the AppDelegate is there a possibility to call the didProcessPriceUpdate from the TipViewController.swift? If yes, would you mind helping me with the code? It's my first Swift project :)

Thanks a million!

**Comment by johnalanwoods** [comment]
Hi Alifar, sorry for slight delay in reaching back to you. 

You are not passing a quote instance to the function but rather the class Quote. 

You need to create a new quote instance and pass that. 

Something like this:

var myQuote:Quote = Quote()
self.didProcessPriceUpdate(myQuote)

Please also note, you need to create a properly populated quote object (see Quote.swift comments). Additionally this is a delegate method intended to be called by a PriceStreamer instance. 

I have a huge update coming to the code which now supports lots of extra features. Let me know how you get on. 

Cheers
John

**Comment by Alifar** [comment]
Hi John,

Can't get it work. I will wait for the new update. When do you think it will be released? I also will add price alerts to it btw.

Rg,

Alifar

**Comment by johnalanwoods** [comment]
Hi Alifar,

It's done now! I have added price alerts and portfolio tracking. It works very nicely!

Screenshots:http://m.imgur.com/a/QFZZJ

It's committed. Download the latest source from the repo. 

The code is a lot more sophisticated now. Let me know if you have questions.
